import json
import os

locales_dir = "/Users/ashwinpugazhendhi/SocialRaven/highshift.cloud-frontend/src/locales"

translations = {
    "en": {
        "profiles": {
            "title": "Profiles",
            "subtitle": "Organize your social accounts into profiles for easy management.",
            "profilesCount": "Profiles",
            "accountsCount": "Accounts",
            "createNew": "Create New Profile",
            "createNewDesc": "Each profile can hold multiple social accounts. Use profiles to separate clients, brands, or teams.",
            "profileNamePlaceholder": "Profile name...",
            "create": "Create",
            "noProfiles": "No profiles yet",
            "createFirstDesc": "Create your first profile above to start connecting social media accounts.",
            "connectedCount": "{{count}} connected account",
            "connectedCount_plural": "{{count}} connected accounts",
            "addAccount": "Add Account",
            "deleteProfile": "Delete Profile",
            "noAccounts": "No accounts connected",
            "connectFirst": "Connect your first account",
            "disconnect": "Disconnect",
            "proTip": "Pro Tip",
            "proTipDesc1": "You can use our ",
            "proTipDesc2": " API to automate profile creation and posting.",
            "viewApiDoc": "View API Documentation"
        },
        "ai_studio": {
            "initialMessage": "I am your Social Raven AI Creative Assistant. I can generate high-impact posts or create visuals. Just ask me to 'write a post about...' or 'generate an image of...'.",
            "tones": {
                "professional": "Professional",
                "witty": "Witty",
                "bold": "Bold",
                "empathetic": "Empathetic",
                "minimal": "Minimal"
            },
            "errorConnection": "My connection to the neural net was interrupted. Please try again.",
            "title": "Social Raven AI",
            "subtitle": "Multi-modal Creative Engine",
            "generatedBy": "Generated by Social Raven AI",
            "openFull": "Open Full",
            "copy": "Copy",
            "schedule": "Schedule",
            "retry": "Retry",
            "placeholder": "Ask: 'Write a tweet about launch...' or 'Generate an image of a futuristic city...'",
            "generate": "Generate",
            "poweredBy": "Powered by Social Raven AI Models"
        },
        "publisher": {
            "postAsProfile": "Post As (Profile)",
            "selectAccounts": "Select Accounts",
            "startWriting": "Start writing your post...",
            "schedulingOptions": "Scheduling Options",
            "saveDraft": "Save Draft",
            "processing": "Processing...",
            "schedulePost": "Schedule Post",
            "publishNow": "Publish Now",
            "networkPreview": "Network Preview",
            "mobile": "Mobile",
            "desktop": "Desktop",
            "previewDisclaimer": "Preview approximates how your content will display. Social networks may update their UI at any time."
        }
    },
    "es": {
        "profiles": {
            "title": "Perfiles",
            "subtitle": "Organiza tus cuentas sociales en perfiles para facilitar su gestión.",
            "profilesCount": "Perfiles",
            "accountsCount": "Cuentas",
            "createNew": "Crear Nuevo Perfil",
            "createNewDesc": "Cada perfil puede contener múltiples cuentas sociales. Usa perfiles para separar clientes, marcas o equipos.",
            "profileNamePlaceholder": "Nombre del perfil...",
            "create": "Crear",
            "noProfiles": "Aún no hay perfiles",
            "createFirstDesc": "Crea tu primer perfil arriba para comenzar a conectar cuentas de redes sociales.",
            "connectedCount": "{{count}} cuenta conectada",
            "connectedCount_plural": "{{count}} cuentas conectadas",
            "addAccount": "Añadir Cuenta",
            "deleteProfile": "Eliminar Perfil",
            "noAccounts": "No hay cuentas conectadas",
            "connectFirst": "Conecta tu primera cuenta",
            "disconnect": "Desconectar",
            "proTip": "Consejo Profesional",
            "proTipDesc1": "Puedes usar nuestra ",
            "proTipDesc2": " API para automatizar la creación de perfiles y publicaciones.",
            "viewApiDoc": "Ver Documentación de la API"
        },
        "ai_studio": {
            "initialMessage": "Soy tu Asistente Creativo de Social Raven AI. Puedo generar publicaciones de alto impacto o crear elementos visuales. Solo pídeme que 'escriba una publicación sobre...' o 'genere una imagen de...'.",
            "tones": {
                "professional": "Profesional",
                "witty": "Ingenioso",
                "bold": "Audaz",
                "empathetic": "Empático",
                "minimal": "Minimalista"
            },
            "errorConnection": "Mi conexión a la red neuronal fue interrumpida. Por favor, inténtalo de nuevo.",
            "title": "IA de Social Raven",
            "subtitle": "Motor Creativo Multimodal",
            "generatedBy": "Generado por la IA de Social Raven",
            "openFull": "Abrir Completo",
            "copy": "Copiar",
            "schedule": "Programar",
            "retry": "Reintentar",
            "placeholder": "Pregunta: 'Escribe un tweet sobre el lanzamiento...' o 'Genera una imagen de una ciudad futurista...'",
            "generate": "Generar",
            "poweredBy": "Desarrollado por Modelos de IA de Social Raven"
        },
        "publisher": {
            "postAsProfile": "Publicar Como (Perfil)",
            "selectAccounts": "Seleccionar Cuentas",
            "startWriting": "Comienza a escribir tu publicación...",
            "schedulingOptions": "Opciones de Programación",
            "saveDraft": "Guardar Borrador",
            "processing": "Procesando...",
            "schedulePost": "Programar Publicación",
            "publishNow": "Publicar Ahora",
            "networkPreview": "Vista Previa de la Red",
            "mobile": "Móvil",
            "desktop": "Escritorio",
            "previewDisclaimer": "La vista previa aproxima cómo se mostrará tu contenido. Las redes sociales pueden actualizar su interfaz en cualquier momento."
        }
    },
    "fr": {
        "profiles": {
            "title": "Profils",
            "subtitle": "Organisez vos comptes sociaux en profils pour une gestion facile.",
            "profilesCount": "Profils",
            "accountsCount": "Comptes",
            "createNew": "Créer un Nouveau Profil",
            "createNewDesc": "Chaque profil peut contenir plusieurs comptes sociaux. Utilisez les profils pour séparer clients, marques ou équipes.",
            "profileNamePlaceholder": "Nom du profil...",
            "create": "Créer",
            "noProfiles": "Pas encore de profils",
            "createFirstDesc": "Créez votre premier profil ci-dessus pour commencer à connecter des comptes de réseaux sociaux.",
            "connectedCount": "{{count}} compte connecté",
            "connectedCount_plural": "{{count}} comptes connectés",
            "addAccount": "Ajouter un Compte",
            "deleteProfile": "Supprimer le Profil",
            "noAccounts": "Aucun compte connecté",
            "connectFirst": "Connectez votre premier compte",
            "disconnect": "Déconnecter",
            "proTip": "Astuce de Pro",
            "proTipDesc1": "Vous pouvez utiliser notre API ",
            "proTipDesc2": " pour automatiser la création de profils et de publications.",
            "viewApiDoc": "Voir la Documentation de l'API"
        },
        "ai_studio": {
            "initialMessage": "Je suis votre Assistant Créatif Social Raven AI. Je peux générer des publications à fort impact ou créer des visuels. Demandez-moi simplement de 'écrire un post sur...' ou 'générer une image de...'.",
            "tones": {
                "professional": "Professionnel",
                "witty": "Spirituel",
                "bold": "Audacieux",
                "empathetic": "Empathique",
                "minimal": "Minimaliste"
            },
            "errorConnection": "Ma connexion au réseau neuronal a été interrompue. Veuillez réessayer.",
            "title": "IA de Social Raven",
            "subtitle": "Moteur Créatif Multimodal",
            "generatedBy": "Généré par l'IA de Social Raven",
            "openFull": "Ouvrir en Entier",
            "copy": "Copier",
            "schedule": "Programmer",
            "retry": "Réessayer",
            "placeholder": "Demandez : 'Écris un tweet sur le lancement...' ou 'Génère une image d'une ville futuriste...'",
            "generate": "Générer",
            "poweredBy": "Propulsé par les Modèles d'IA Social Raven"
        },
        "publisher": {
            "postAsProfile": "Publier en tant que (Profil)",
            "selectAccounts": "Sélectionner des Comptes",
            "startWriting": "Commencez à écrire votre publication...",
            "schedulingOptions": "Options de Programmation",
            "saveDraft": "Enregistrer le Brouillon",
            "processing": "Traitement en cours...",
            "schedulePost": "Programmer la Publication",
            "publishNow": "Publier Maintenant",
            "networkPreview": "Aperçu du Réseau",
            "mobile": "Mobile",
            "desktop": "Bureau",
            "previewDisclaimer": "L'aperçu donne une idée de l'affichage de votre contenu. Les réseaux sociaux peuvent modifier leur interface à tout moment."
        }
    },
    "de": {
        "profiles": {
            "title": "Profile",
            "subtitle": "Organisieren Sie Ihre sozialen Konten in Profilen zur einfachen Verwaltung.",
            "profilesCount": "Profile",
            "accountsCount": "Konten",
            "createNew": "Neues Profil Erstellen",
            "createNewDesc": "Jedes Profil kann mehrere soziale Konten aufnehmen. Nutzen Sie Profile, um Kunden, Marken oder Teams zu trennen.",
            "profileNamePlaceholder": "Profilname...",
            "create": "Erstellen",
            "noProfiles": "Noch keine Profile",
            "createFirstDesc": "Erstellen Sie oben Ihr erstes Profil, um Social-Media-Konten zu verbinden.",
            "connectedCount": "{{count}} verbundenes Konto",
            "connectedCount_plural": "{{count}} verbundene Konten",
            "addAccount": "Konto Hinzufügen",
            "deleteProfile": "Profil Löschen",
            "noAccounts": "Keine Konten verbunden",
            "connectFirst": "Verbinden Sie Ihr erstes Konto",
            "disconnect": "Trennen",
            "proTip": "Profi-Tipp",
            "proTipDesc1": "Sie können unsere ",
            "proTipDesc2": " API nutzen, um die Profilerstellung und das Posten zu automatisieren.",
            "viewApiDoc": "API-Dokumentation Ansehen"
        },
        "ai_studio": {
            "initialMessage": "Ich bin Ihr Social Raven AI Creative Assistant. Ich kann wirkungsvolle Beiträge oder visuelle Inhalte erstellen. Bitten Sie mich einfach, 'einen Beitrag zu schreiben über...' oder 'ein Bild zu generieren von...'.",
            "tones": {
                "professional": "Professionell",
                "witty": "Witzig",
                "bold": "Mutig",
                "empathetic": "Empathisch",
                "minimal": "Minimalistisch"
            },
            "errorConnection": "Meine Verbindung zum neuronalen Netz wurde unterbrochen. Bitte versuchen Sie es erneut.",
            "title": "Social Raven KI",
            "subtitle": "Multimodale Kreativ-Engine",
            "generatedBy": "Generiert von Social Raven KI",
            "openFull": "Vollständig Öffnen",
            "copy": "Kopieren",
            "schedule": "Planen",
            "retry": "Wiederholen",
            "placeholder": "Fragen Sie: 'Schreibe einen Tweet über den Launch...' oder 'Generiere ein Bild einer futuristischen Stadt...'",
            "generate": "Generieren",
            "poweredBy": "Unterstützt durch Social Raven KI-Modelle"
        },
        "publisher": {
            "postAsProfile": "Posten Als (Profil)",
            "selectAccounts": "Konten Auswählen",
            "startWriting": "Beginnen Sie mit dem Schreiben Ihres Beitrags...",
            "schedulingOptions": "Planungsoptionen",
            "saveDraft": "Entwurf Speichern",
            "processing": "Wird bearbeitet...",
            "schedulePost": "Beitrag Planen",
            "publishNow": "Jetzt Veröffentlichen",
            "networkPreview": "Netzwerk-Vorschau",
            "mobile": "Mobil",
            "desktop": "Desktop",
            "previewDisclaimer": "Die Vorschau zeigt annähernd, wie Ihr Inhalt angezeigt wird. Soziale Netzwerke können ihre Benutzeroberfläche jederzeit aktualisieren."
        }
    },
    "ar": {
        "profiles": {
            "title": "الملفات الشخصية",
            "subtitle": "نظم حساباتك الاجتماعية في ملفات شخصية لسهولة الإدارة.",
            "profilesCount": "الملفات الشخصية",
            "accountsCount": "الحسابات",
            "createNew": "إنشاء ملف شخصي جديد",
            "createNewDesc": "يمكن لكل ملف شخصي أن يحتوي على حسابات اجتماعية متعددة. استخدم الملفات الشخصية لفصل العملاء أو العلامات التجارية أو الفرق.",
            "profileNamePlaceholder": "اسم الملف الشخصي...",
            "create": "إنشاء",
            "noProfiles": "لا توجد ملفات شخصية بعد",
            "createFirstDesc": "قم بإنشاء ملفك الشخصي الأول أعلاه للبدء في ربط حسابات وسائل التواصل الاجتماعي.",
            "connectedCount": "{{count}} حساب متصل",
            "connectedCount_plural": "{{count}} حسابات متصلة",
            "addAccount": "إضافة حساب",
            "deleteProfile": "حذف الملف الشخصي",
            "noAccounts": "لا توجد حسابات متصلة",
            "connectFirst": "قم بتوصيل حسابك الأول",
            "disconnect": "قطع الاتصال",
            "proTip": "نصيحة احترافية",
            "proTipDesc1": "يمكنك استخدام ",
            "proTipDesc2": " API الخاصة بنا لأتمتة إنشاء الملفات الشخصية والنشر.",
            "viewApiDoc": "عرض وثائق API"
        },
        "ai_studio": {
            "initialMessage": "أنا مساعدك الإبداعي Social Raven AI. يمكنني إنشاء منشورات عالية التأثير أو صور. فقط اطلب مني 'كتابة منشور حول...' أو 'توليد صورة لـ...'.",
            "tones": {
                "professional": "احترافي",
                "witty": "ذكي",
                "bold": "جريء",
                "empathetic": "متعاطف",
                "minimal": "بسيط"
            },
            "errorConnection": "تم قطع اتصالي بالشبكة العصبية. يرجى المحاولة مرة أخرى.",
            "title": "ذكاء Social Raven الاصطناعي",
            "subtitle": "محرك إبداعي متعدد الوسائط",
            "generatedBy": "تم الإنشاء بواسطة ذكاء Social Raven الاصطناعي",
            "openFull": "فتح بالكامل",
            "copy": "نسخ",
            "schedule": "جدولة",
            "retry": "إعادة المحاولة",
            "placeholder": "اسأل: 'اكتب تغريدة عن الإطلاق...' أو 'قم بتوليد صورة لمدينة مستقبلية...'",
            "generate": "توليد",
            "poweredBy": "مدعوم بنماذج ذكاء Social Raven الاصطناعي"
        },
        "publisher": {
            "postAsProfile": "انشر كـ (ملف شخصي)",
            "selectAccounts": "اختر الحسابات",
            "startWriting": "ابدأ بكتابة منشورك...",
            "schedulingOptions": "خيارات الجدولة",
            "saveDraft": "حفظ كمسودة",
            "processing": "جاري المعالجة...",
            "schedulePost": "جدولة المنشور",
            "publishNow": "انشر الآن",
            "networkPreview": "معاينة الشبكة",
            "mobile": "هاتف",
            "desktop": "سطح المكتب",
            "previewDisclaimer": "تقارب المعاينة كيفية عرض المحتوى الخاص بك. قد تقوم الشبكات الاجتماعية بتحديث واجهة المستخدم الخاصة بها في أي وقت."
        }
    },
    "zh": {
        "profiles": {
            "title": "简介",
            "subtitle": "将您的社交帐户组织到配置文件中以便于管理。",
            "profilesCount": "配置文件",
            "accountsCount": "帐户",
            "createNew": "创建新配置文件",
            "createNewDesc": "每个配置文件可以容纳多个社交帐户。使用配置文件来区分客户、品牌或团队。",
            "profileNamePlaceholder": "配置文件名称...",
            "create": "创建",
            "noProfiles": "暂无配置文件",
            "createFirstDesc": "在上方创建您的第一个配置文件以开始连接社交媒体帐户。",
            "connectedCount": "{{count}} 个已连接帐户",
            "connectedCount_plural": "{{count}} 个已连接帐户",
            "addAccount": "添加帐户",
            "deleteProfile": "删除配置文件",
            "noAccounts": "未连接任何帐户",
            "connectFirst": "连接您的第一个帐户",
            "disconnect": "断开连接",
            "proTip": "专业提示",
            "proTipDesc1": "您可以使用我们的 ",
            "proTipDesc2": " API 自动创建配置文件和发布内容。",
            "viewApiDoc": "查看 API 文档"
        },
        "ai_studio": {
            "initialMessage": "我是您的 Social Raven AI 创意助手。我可以生成高影响力的帖子或创建视觉内容。只需让我“写一篇关于……的帖子”或“生成一张……的图片”。",
            "tones": {
                "professional": "专业",
                "witty": "风趣",
                "bold": "大胆",
                "empathetic": "共情",
                "minimal": "极简"
            },
            "errorConnection": "我与神经网络的连接已中断。请重试。",
            "title": "Social Raven AI",
            "subtitle": "多模态创意引擎",
            "generatedBy": "由 Social Raven AI 生成",
            "openFull": "全屏打开",
            "copy": "复制",
            "schedule": "安排",
            "retry": "重试",
            "placeholder": "提问：'写一条关于发布的推文...' 或 '生成一张未来城市的图片...'",
            "generate": "生成",
            "poweredBy": "由 Social Raven AI 模型驱动"
        },
        "publisher": {
            "postAsProfile": "作为（配置文件）发布",
            "selectAccounts": "选择帐户",
            "startWriting": "开始编写您的帖子...",
            "schedulingOptions": "发布安排选项",
            "saveDraft": "保存草稿",
            "processing": "处理中...",
            "schedulePost": "安排帖子",
            "publishNow": "立即发布",
            "networkPreview": "网络预览",
            "mobile": "移动端",
            "desktop": "桌面端",
            "previewDisclaimer": "预览仅反映内容的近似显示效果。社交网络可能随时更新其用户界面。"
        }
    }
}

for lang, data in translations.items():
    filepath = os.path.join(locales_dir, f"{lang}.json")
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            current_data = json.load(f)
        
        current_data.update(data)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(current_data, f, ensure_ascii=False, indent=2)
            
print("Locales updated successfully!")
