import FeaturePageTemplate from '../../components/FeaturePageTemplate';
import { Users, Share2, Award, Trophy, ShieldCheck, Smartphone } from 'lucide-react';

export default function Advocacy() {
    const features = [
        {
            title: "Curated Content Hub",
            description: "Give your employees a pre-approved library of content they can share to their personal networks in one click.",
            icon: Share2
        },
        {
            title: "Gamification",
            description: "Drive adoption with leaderboards and point systems. Reward your top sharing employees.",
            icon: Trophy
        },
        {
            title: "Performance Tracking",
            description: "Measure the Earned Media Value (EMV) generated by your employee advocacy program.",
            icon: Award
        },
        {
            title: "Compliance & Safety",
            description: "Ensure all shared content meets brand guidelines. Lock captions or images for sensitive announcements.",
            icon: ShieldCheck
        },
        {
            title: "Mobile First",
            description: "Employees can share content on-the-go with our dedicated mobile app.",
            icon: Smartphone
        },
        {
            title: "Talent Branding",
            description: "Position your employees as thought leaders, attracting top talent to your company.",
            icon: Users
        }
    ];

    return (
        <FeaturePageTemplate
            title="Employee Advocacy"
            subtitle="Amplify your reach by 10x. Empower your workforce to become your most powerful marketing channel."
            heroGradient="from-pink-500 to-rose-500"
            features={features}
        />
    );
}
